### ISSUE TITLE
Configure Justext without any specified language

### ISSUE THREAD

**Issue by xyNNN** [miso-belica/jusText#12]
I just wonder, if it's possible to start the parsing process without to define any specified language like in the [Example] (http://nlp.fi.muni.cz/projects/justext/?url=http://www.laichingen.de/de/Aktuelles/Aktuelle-News/News?view=publish&item=article&id=1051&language=-Any_language-&no_headings=on&max_heading_distance=200&length_low=70&length_high=200&stopwords_low=0.3&stopwords_high=0.32&max_link_density=0.2&language=any_language).

My current configuration for Justext looks like the following

`justext.justext(page, justext.get_stoplist("German"), 99, 100, 0.1, 0.32, 0.2, 200, True)`

**Comment by miso-belica** [comment]
Hi, you can set stopwords into empty set/list/... like this:
```py
justext.justext(page, frozenset(), 99, 100, 0.1, 0.32, 0.2, 200, True)
```

**Comment by xyNNN** [comment]
I'm getting an empty response, any other solutions?

**Comment by miso-belica** [comment]
Yes, that's correct response. Web interface gives you empty response too because given page contains no useful text.

**Comment by xyNNN** [comment]
But my response differs from the response from the web interface after changing the stoplist to frozenset() - so something is not working correctly.

**Comment by miso-belica** [comment]
Differs how? Please provide as much info as possible.

**Comment by xyNNN** [comment]
When i use the following configuration i get for the URL http://www.efinancialcareers.de/jobs-Deutschland-Berlin-Spezialist-in_Banksteuerung_Meldewesen_MaRisk.id00903684 an empty response.
With the web interface i get the wanted information from the given URI.

paragraphs = justext.justext(page, frozenset(), 99, 100, 0.1, 0.32, 0.2, 200, True)

**Comment by miso-belica** [comment]
Following works for me. But I have no idea how the web interface is implementing it. I have no access to it.
```python
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import division, print_function, unicode_literals

import requests
import justext


def main():
    response = requests.get(
        "http://www.efinancialcareers.de/jobs-Deutschland-Berlin-"
        "Spezialist-in_Banksteuerung_Meldewesen_MaRisk.id00903684"
    )
    response.raise_for_status()
    page = response.content
    any_lang_stop_words = get_all_stop_words()

    paragraphs = justext.justext(page, any_lang_stop_words, 99, 100, 0.1, 0.32, 0.2, 200, True)
    for paragraph in paragraphs:
        if not paragraph.is_boilerplate:
            print(paragraph.text.encode("utf-8"))

    return 0


def get_all_stop_words():
    stop_words = set()
    for language in justext.get_stoplists():
        stop_words.update(justext.get_stoplist(language))

    return stop_words


if __name__ == "__main__":
    exit(main())
```
