### ISSUE TITLE
No newline when there should be

### ISSUE THREAD

**Issue by AWNystrom** [miso-belica/jusText#14]
Hello,

If I do the following:

```python
>>> import justext
>>> doc = """Any update on this Akosha??
I want to take this complaint forward to the consumer forum."""
>>> '\n'.join(p.text for p in justext.justext(doc, []))
u'Any update on this Akosha??I want to take this complaint forward to the consumer forum.'
```
why is there not a newline between "Akosha??" and "I want"?

**Comment by AWNystrom** [comment]
Github removed the < br > tag, but there should be one in the specified place.

**Comment by miso-belica** [comment]
@AWNystrom thanks for the report. I think this is the bug and I hope I'll fix it tomorow. I'm busy right now.
