### ISSUE TITLE
justext: previous call leaks into the parser

### ISSUE THREAD

**Issue by enku** [miso-belica/jusText#17]
There is an issue (really lxml's fault) with `core.justext()` whereby, lxml uses a "global" (module-level) HTML parser in `lxml.html.fromstring()` by default if a parser is not passed.  When you pass "partial" html, then it is fed to the global parser, and in subsequent calls continue to feed the global parser.  I'm not sure if this is a "bug" in lxml or a feature.  However it affects gettext in that it gives unexpected and non-deterministic results::

    >>> justext.justext('<justext></justext>', justext.get_stoplist('English'))
    ➥  []
    >>> justext.justext('', justext.get_stoplist('English'))
      File "<string>", line unknown
    XMLSyntaxError: line 1: Tag justext invalid

This can be worked around by passing a new instance to `lxml.html.fromstring()` whenever it is called:

```diff
diff --git a/justext/core.py b/justext/core.py
index bc34691..2dbe75f 100644
--- a/justext/core.py
+++ b/justext/core.py
@@ -60,11 +60,11 @@ def html_to_dom(html, default_encoding=DEFAULT_ENCODING, encoding=None, errors=D
         decoded_html = decode_html(html, default_encoding, encoding, errors)
 
     try:
-        dom = lxml.html.fromstring(decoded_html)
+        dom = lxml.html.fromstring(decoded_html, parser=lxml.html.HTMLParser())
     except ValueError:
         # Unicode strings with encoding declaration are not supported.
         # for XHTML files with encoding declaration, use the declared encoding
-        dom = lxml.html.fromstring(html)
+        dom = lxml.html.fromstring(html, parser=lxml.html.HTMLParser())
 
     return dom

```

    >>> import justext
    >>> justext.justext('<justext></justext>', justext.get_stoplist('English'))
    ➥  []
    >>> justext.justext('', justext.get_stoplist('English'))
      File "<string>", line unknown
    XMLSyntaxError

In this (contrived) example we still get an error, but it's somewhat expected and deterministic.

**Comment by miso-belica** [comment]
@enku Thanks for this. I'll look at it soon (I hope).
