### ISSUE TITLE
Change parameter through Python API

### ISSUE THREAD

**Issue by cklat** [miso-belica/jusText#23]
I'm currently using jusText in one of my projects that is written in python. Through the online demo, I experimentally found out that slightly changed parameters work better for me than the default settings for them. So, I'm currently wondering how to change these when using jusText in python? I'm referring to the parameters 'length low', 'stopwords low' and so on, to be clear.

Thanks!

**Comment by miso-belica** [comment]
Hi, you can change [any parameters you want](https://github.com/miso-belica/jusText/blob/dev/justext/core.py#L359-L364) when calling justext from your code ;)
